// Copyright (c) 2026 MoeGodot<me@kawayi.moe>.
// Licensed under the GNU Affero General Public License v3-or-later license.

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Kawayi.CommandLine.Generator;

/// <summary>
/// Generates <c>IDocumentExporter</c> implementations for types annotated with
/// <c>ExportDocumentAttribute</c> or <c>CommandAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ExportDocumentGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var explicitTargets = context.SyntaxProvider.ForAttributeWithMetadataName(
            MetadataNames.ExportDocumentAttribute,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
                CreateTarget(syntaxContext, skipCommandTargets: true, cancellationToken));

        var commandTargets = context.SyntaxProvider.ForAttributeWithMetadataName(
            MetadataNames.CommandAttribute,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
                CreateTarget(syntaxContext, skipCommandTargets: false, cancellationToken));

        context.RegisterSourceOutput(explicitTargets.Where(static target => target is not null),
                                     static (productionContext, target) => Emit(productionContext, target!));
        context.RegisterSourceOutput(commandTargets.Where(static target => target is not null),
                                     static (productionContext, target) => Emit(productionContext, target!));
    }

    private static CommandModel? CreateTarget(
        GeneratorAttributeSyntaxContext context,
        bool skipCommandTargets,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (skipCommandTargets && CommandModel.HasAttribute(typeSymbol, MetadataNames.CommandAttribute))
        {
            return null;
        }

        var model = CommandModel.Create(typeSymbol, cancellationToken);
        if (model.HasCommandAttribute &&
            !model.HasExportDocumentAttribute &&
            model.ImplementsDocumentExporter)
        {
            return null;
        }

        return model;
    }

    private static void Emit(SourceProductionContext context, CommandModel model)
    {
        if (model.MissingPartialSymbol is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                GeneratorDescriptors.DocumentNonPartial,
                model.MissingPartialSymbol.Locations.FirstOrDefault(),
                model.MissingPartialSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
            return;
        }

        context.AddSource(
            GeneratorSource.GetHintName(model.TypeSymbol, "ExportDocument"),
            SourceText.From(GenerateSource(model), Encoding.UTF8));
    }

    private static string GenerateSource(CommandModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");

        if (!model.TypeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").Append(model.TypeSymbol.ContainingNamespace.ToDisplayString()).AppendLine();
            builder.AppendLine("{");
        }

        var containingTypes = GeneratorSource.GetContainingTypes(model.TypeSymbol);
        for (var i = 0; i < containingTypes.Length; i++)
        {
            GeneratorSource.AppendIndentedLine(builder, i, GeneratorSource.BuildTypeDeclaration(containingTypes[i], null, includeInterface: false));
            GeneratorSource.AppendIndentedLine(builder, i, "{");
        }

        var interfaceList = model.ImplementsDocumentExporter
            ? null
            : "global::Kawayi.CommandLine.Abstractions.IDocumentExporter";
        GeneratorSource.AppendIndentedLine(builder, containingTypes.Length, GeneratorSource.BuildTypeDeclaration(model.TypeSymbol, interfaceList, includeInterface: true));
        GeneratorSource.AppendIndentedLine(builder, containingTypes.Length, "{");
        AppendDocumentsProperty(builder, model, containingTypes.Length + 1);
        GeneratorSource.AppendIndentedLine(builder, containingTypes.Length, "}");

        for (var i = containingTypes.Length - 1; i >= 0; i--)
        {
            GeneratorSource.AppendIndentedLine(builder, i, "}");
        }

        if (!model.TypeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void AppendDocumentsProperty(StringBuilder builder, CommandModel model, int indentLevel)
    {
        GeneratorSource.AppendIndentedLine(builder, indentLevel, "/// <summary>");
        GeneratorSource.AppendIndentedLine(builder, indentLevel, "/// Gets the generated documentation entries for this command type.");
        GeneratorSource.AppendIndentedLine(builder, indentLevel, "/// </summary>");
        const string propertyHeader =
            "public static global::System.Collections.Immutable.ImmutableDictionary<string, global::Kawayi.CommandLine.Abstractions.Document> Documents { get; } = ";

        var members = model.Members.OrderBy(static member => member.DeclarationOrder).ToImmutableArray();
        if (members.Length == 0)
        {
            GeneratorSource.AppendIndentedLine(
                builder,
                indentLevel,
                propertyHeader +
                "global::System.Collections.Immutable.ImmutableDictionary<string, global::Kawayi.CommandLine.Abstractions.Document>.Empty;");
            return;
        }

        GeneratorSource.AppendIndentedLine(builder, indentLevel, propertyHeader);
        GeneratorSource.AppendIndentedLine(
            builder,
            indentLevel + 1,
            "global::System.Collections.Immutable.ImmutableDictionary.CreateRange<string, global::Kawayi.CommandLine.Abstractions.Document>(");
        GeneratorSource.AppendIndentedLine(
            builder,
            indentLevel + 2,
            "new global::System.Collections.Generic.KeyValuePair<string, global::Kawayi.CommandLine.Abstractions.Document>[]");
        GeneratorSource.AppendIndentedLine(builder, indentLevel + 2, "{");

        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            var trailingComma = i == members.Length - 1 ? string.Empty : ",";
            var entry =
                $"new({SymbolDisplay.FormatLiteral(member.MemberName, true)}, new global::Kawayi.CommandLine.Abstractions.Document({SymbolDisplay.FormatLiteral(member.Summary, true)}, {SymbolDisplay.FormatLiteral(member.Remarks, true)})){trailingComma}";
            GeneratorSource.AppendIndentedLine(builder, indentLevel + 3, entry);
        }

        GeneratorSource.AppendIndentedLine(builder, indentLevel + 2, "}");
        GeneratorSource.AppendIndentedLine(builder, indentLevel + 1, ");");
    }
}
