// Copyright (c) 2026 MoeGodot<me@kawayi.moe>.
// Licensed under the GNU Affero General Public License v3-or-later license.

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Kawayi.CommandLine.Generator;

/// <summary>
/// Generates <c>ISymbolExporter</c> implementations for types annotated with
/// <c>ExportSymbolsAttribute</c> or <c>CommandAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ExportSymbolsGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var explicitTargets = context.SyntaxProvider.ForAttributeWithMetadataName(
            MetadataNames.ExportSymbolsAttribute,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
                CreateTarget(syntaxContext, skipCommandTargets: true, cancellationToken));

        var commandTargets = context.SyntaxProvider.ForAttributeWithMetadataName(
            MetadataNames.CommandAttribute,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
            transform: static (syntaxContext, cancellationToken) =>
                CreateTarget(syntaxContext, skipCommandTargets: false, cancellationToken));

        context.RegisterSourceOutput(explicitTargets.Where(static target => target is not null),
                                     static (productionContext, target) => Emit(productionContext, target!));
        context.RegisterSourceOutput(commandTargets.Where(static target => target is not null),
                                     static (productionContext, target) => Emit(productionContext, target!));
    }

    private static CommandModel? CreateTarget(
        GeneratorAttributeSyntaxContext context,
        bool skipCommandTargets,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (skipCommandTargets && CommandModel.HasAttribute(typeSymbol, MetadataNames.CommandAttribute))
        {
            return null;
        }

        return CommandModel.Create(typeSymbol, cancellationToken);
    }

    private static void Emit(SourceProductionContext context, CommandModel model)
    {
        if (model.MissingPartialSymbol is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                GeneratorDescriptors.SymbolsNonPartial,
                model.MissingPartialSymbol.Locations.FirstOrDefault(),
                model.MissingPartialSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
            return;
        }

        if (!model.HasDocumentProvider)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                GeneratorDescriptors.MissingDocumentExporter,
                model.TypeSymbol.Locations.FirstOrDefault(),
                model.TypeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
            return;
        }

        foreach (var diagnostic in model.SymbolDiagnostics)
        {
            context.ReportDiagnostic(Diagnostic.Create(diagnostic.Descriptor, diagnostic.Location, diagnostic.Arguments));
        }

        if (model.SymbolDiagnostics.Any(static diagnostic =>
                diagnostic.Descriptor.DefaultSeverity == DiagnosticSeverity.Error))
        {
            return;
        }

        context.AddSource(
            GeneratorSource.GetHintName(model.TypeSymbol, "ExportSymbols"),
            SourceText.From(GenerateSource(model), Encoding.UTF8));
    }

    private static string GenerateSource(CommandModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");

        if (!model.TypeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ").Append(model.TypeSymbol.ContainingNamespace.ToDisplayString()).AppendLine();
            builder.AppendLine("{");
        }

        var containingTypes = GeneratorSource.GetContainingTypes(model.TypeSymbol);
        for (var i = 0; i < containingTypes.Length; i++)
        {
            GeneratorSource.AppendIndentedLine(builder, i, GeneratorSource.BuildTypeDeclaration(containingTypes[i], null, includeInterface: false));
            GeneratorSource.AppendIndentedLine(builder, i, "{");
        }

        var interfaceList = model.ImplementsSymbolExporter
            ? null
            : "global::Kawayi.CommandLine.Abstractions.ISymbolExporter";
        GeneratorSource.AppendIndentedLine(builder, containingTypes.Length, GeneratorSource.BuildTypeDeclaration(model.TypeSymbol, interfaceList, includeInterface: true));
        GeneratorSource.AppendIndentedLine(builder, containingTypes.Length, "{");
        AppendSymbolsProperty(builder, model, containingTypes.Length + 1);
        GeneratorSource.AppendIndentedLine(builder, containingTypes.Length, "}");

        for (var i = containingTypes.Length - 1; i >= 0; i--)
        {
            GeneratorSource.AppendIndentedLine(builder, i, "}");
        }

        if (!model.TypeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void AppendSymbolsProperty(StringBuilder builder, CommandModel model, int indentLevel)
    {
        GeneratorSource.AppendIndentedLine(builder, indentLevel, "/// <summary>");
        GeneratorSource.AppendIndentedLine(builder, indentLevel, "/// Gets the generated command-line symbol definitions for this command type.");
        GeneratorSource.AppendIndentedLine(builder, indentLevel, "/// </summary>");
        const string propertyHeader =
            "public static global::System.Collections.Immutable.ImmutableArray<global::Kawayi.CommandLine.Abstractions.Symbol> Symbols { get; } = ";

        if (model.Members.IsDefaultOrEmpty)
        {
            GeneratorSource.AppendIndentedLine(
                builder,
                indentLevel,
                propertyHeader +
                "global::System.Collections.Immutable.ImmutableArray<global::Kawayi.CommandLine.Abstractions.Symbol>.Empty;");
            return;
        }

        GeneratorSource.AppendIndentedLine(builder, indentLevel, propertyHeader);
        GeneratorSource.AppendIndentedLine(
            builder,
            indentLevel + 1,
            "global::System.Collections.Immutable.ImmutableArray.Create<global::Kawayi.CommandLine.Abstractions.Symbol>(");

        var orderedMembers = OrderMembers(model.Members);
        for (var i = 0; i < orderedMembers.Length; i++)
        {
            var trailingComma = i == orderedMembers.Length - 1 ? string.Empty : ",";
            GeneratorSource.AppendIndentedLine(builder, indentLevel + 2, GenerateSymbolExpression(orderedMembers[i]) + trailingComma);
        }

        GeneratorSource.AppendIndentedLine(builder, indentLevel + 1, ");");
    }

    private static ImmutableArray<MemberModel> OrderMembers(ImmutableArray<MemberModel> members)
    {
        return [.. members.Where(static member => member.Kind == MemberKind.Argument)
            .OrderBy(static member => member.ArgumentPosition)
            .ThenBy(static member => member.DeclarationOrder)
            .Concat(members.Where(static member => member.Kind == MemberKind.Property)
                .OrderBy(static member => member.DeclarationOrder))
            .Concat(members.Where(static member => member.Kind == MemberKind.Subcommand)
                .OrderBy(static member => member.DeclarationOrder))];
    }

    private static string GenerateSymbolExpression(MemberModel member)
    {
        return member.Kind switch
        {
            MemberKind.Argument => GenerateArgumentExpression(member),
            MemberKind.Property => GeneratePropertyExpression(member),
            MemberKind.Subcommand => GenerateSubcommandExpression(member),
            _ => throw new ArgumentOutOfRangeException(nameof(member.Kind)),
        };
    }

    private static string GenerateArgumentExpression(MemberModel member)
    {
        var argumentExpression =
            $"new global::Kawayi.CommandLine.Abstractions.ArgumentDefinition({GenerateDefinitionInformationExpression(member)}, null, new global::Kawayi.CommandLine.Abstractions.ValueRange({member.ValueRangeMinimum}, {member.ValueRangeMaximum}), typeof({member.TypeName}), {FormatBool(member.VisibleRequirement)}, {FormatBool(member.RequirementIfNull)})";
        var initializers = new List<string>(1);
        AddValidationInitializer(initializers, member);

        return ApplyInitializers(argumentExpression, initializers);
    }

    private static string GeneratePropertyExpression(MemberModel member)
    {
        var propertyExpression =
            $"new global::Kawayi.CommandLine.Abstractions.PropertyDefinition({GenerateDefinitionInformationExpression(member)}, {GenerateAliasDictionaryExpression(member.LongAliases)}, {GenerateAliasDictionaryExpression(member.ShortAliases)}, null, typeof({member.TypeName}), {FormatBool(member.VisibleRequirement)}, {FormatBool(member.RequirementIfNull)})";
        var initializers = new List<string>(4);

        if (member.ValueName is not null)
        {
            initializers.Add($"ValueName = {SymbolDisplay.FormatLiteral(member.ValueName, true)}");
        }

        if (member.ValueRangeMinimum is not null && member.ValueRangeMaximum is not null)
        {
            initializers.Add($"NumArgs = new global::Kawayi.CommandLine.Abstractions.ValueRange({member.ValueRangeMinimum}, {member.ValueRangeMaximum})");
        }

        if (member.EnumPossibleValuesExpression is not null)
        {
            initializers.Add($"PossibleValues = {member.EnumPossibleValuesExpression}");
        }

        AddValidationInitializer(initializers, member);

        return ApplyInitializers(propertyExpression, initializers);
    }

    private static string GenerateSubcommandExpression(MemberModel member)
    {
        return
            $"new global::Kawayi.CommandLine.Abstractions.CommandDefinition({GenerateDefinitionInformationExpression(member)}, {GenerateAliasDictionaryExpression(member.Aliases)}, null)";
    }

    private static string GenerateDefinitionInformationExpression(MemberModel member)
    {
        return
            $"new global::Kawayi.CommandLine.Abstractions.DefinitionInformation(new global::Kawayi.CommandLine.Abstractions.NameWithVisibility({member.CommandLineName}, {FormatBool(member.Visible)}), Documents[{SymbolDisplay.FormatLiteral(member.MemberName, true)}])";
    }

    private static void AddValidationInitializer(List<string> initializers, MemberModel member)
    {
        if (!member.Validators.IsDefaultOrEmpty)
        {
            initializers.Add($"Validation = {GenerateValidationExpression(member)}");
        }
    }

    private static string ApplyInitializers(string expression, List<string> initializers)
    {
        return initializers.Count == 0
            ? expression
            : $"{expression} {{ {string.Join(", ", initializers)} }}";
    }

    private static string GenerateValidationExpression(MemberModel member)
    {
        if (member.Validators.Length == 1)
        {
            return $"static value => {member.Validators[0].MethodName}(({member.TypeName})value)";
        }

        var builder = new StringBuilder();
        builder.Append("static value => { ");
        for (var i = 0; i < member.Validators.Length; i++)
        {
            builder.Append("var result")
                .Append(i)
                .Append(" = ")
                .Append(member.Validators[i].MethodName)
                .Append("((")
                .Append(member.TypeName)
                .Append(")value); if (result")
                .Append(i)
                .Append(" is not null) { return result")
                .Append(i)
                .Append("; } ");
        }

        builder.Append("return null; }");
        return builder.ToString();
    }

    private static string GenerateAliasDictionaryExpression(ImmutableArray<AliasModel> aliases)
    {
        if (aliases.IsDefaultOrEmpty)
        {
            return "global::System.Collections.Immutable.ImmutableDictionary<string, global::Kawayi.CommandLine.Abstractions.NameWithVisibility>.Empty";
        }

        var builder = new StringBuilder();
        builder.Append("global::System.Collections.Immutable.ImmutableDictionary.CreateRange<string, global::Kawayi.CommandLine.Abstractions.NameWithVisibility>(global::System.StringComparer.Ordinal, new global::System.Collections.Generic.KeyValuePair<string, global::Kawayi.CommandLine.Abstractions.NameWithVisibility>[] { ");

        for (var i = 0; i < aliases.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            builder.Append("new(")
                .Append(SymbolDisplay.FormatLiteral(aliases[i].Name, true))
                .Append(", new global::Kawayi.CommandLine.Abstractions.NameWithVisibility(")
                .Append(SymbolDisplay.FormatLiteral(aliases[i].Name, true))
                .Append(", ")
                .Append(FormatBool(aliases[i].Visible))
                .Append("))");
        }

        builder.Append(" })");
        return builder.ToString();
    }

    private static string FormatBool(bool value) => value ? "true" : "false";
}
